name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Exibir arquivos e diretórios a raiz
      run: ls
    - name: Versões do .NET no ambiente
      run: |
        dotnet --list-sdks
        echo '** Versao default do .NET'
        dotnet --version
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.100-preview.7.22377.5
    - name: Versão default após instalação do .NET 7
      run: dotnet --version
